### ISSUE TITLE
Assigning Project User to Departments

### ISSUE THREAD

**Issue by CAMPR-Manuel** [CamprGmbH/campr#135]
**To Reproduce**
When creating a new project and inviting users via the "Organization"-module to the project, the user can create departments and assign invited project users to them by using the "Edit Organization"-Menu (button in the upper right corner within the "Organization"-module. 
This assignment of users to project specific departments is further used in distributing costs (internal and external) to the departments and shown in the cost charts (internal & external cost module, contract, status report). Costs of a individual task are assigned to this department the task responsible user is assigned to. 

But there is a mismatch between what is shown / created within the project via the "Edit Organization"-Menu and the admin section. 
After assigning a user to a department as described above, go to the admin section --> Project --> User and click on "edit user" (pencil button). Under department, the value stays blank! This has to match the assigned department as defined before. Without this (logical) match, the costs charts (by department) are not working. 

**Expected behavior**
Department assignments within the organization module of a project shall match those of "project --> users" in the admin-section, as described above. The cost charts (internal & external) by department shall then display the costs. 

**Screenshots**
<img width="1194" alt="Project Organization" src="https://user-images.githubusercontent.com/63241209/92887419-c16eaa80-f414-11ea-9af0-fdc0082ed17a.png">
<img width="1194" alt="Project Edit Organization" src="https://user-images.githubusercontent.com/63241209/92887472-cfbcc680-f414-11ea-9722-11efd81786b4.png">
<img width="1194" alt="Campr Admin 2" src="https://user-images.githubusercontent.com/63241209/92887492-d3504d80-f414-11ea-9007-799823d505d9.png">
<img width="1194" alt="Campr Admin" src="https://user-images.githubusercontent.com/63241209/92887518-d64b3e00-f414-11ea-8c04-825561aadad1.png">

**Desktop (please complete the following information):**
Any

**Additional context**
-

**Comment by maxlenash** [comment]
done. Deployed to QA

**Comment by cristobalcampr** [comment]
done
