### ISSUE TITLE
"External Costs" - Cost chart by phase not displayed 

### ISSUE THREAD

**Issue by CAMPR-Manuel** [CamprGmbH/campr#136]
**Describe the bug**
Within the "External Costs" module the cost chart by phase is not displayed. While the chart is correctly displayed in the project contract and project status report, it is missing in this module. Only the chart by department is displayed. 

**To Reproduce**
Go in any project with costs assigned to tasks which are then assigned to phases. Click on "External Costs" and the only chart which is displayed is the one by departments. Both charts shall by displayed here, the same layout like on "Internal Costs" 

**Expected behavior**
Cost chart by phases shall by displayed above the cost chart by department within the "External Costs"-Module (Compare "Internal Costs" Module). The chart and data is the same like you can find within the project contract and project status report (External Costs). 

**Screenshots**
<img width="1194" alt="External Costs" src="https://user-images.githubusercontent.com/63241209/92888786-ea436f80-f415-11ea-82a6-6700481a4237.png">
<img width="1194" alt="Internal Costs" src="https://user-images.githubusercontent.com/63241209/92888795-eca5c980-f415-11ea-9af1-4789e7fac9af.png">
<img width="1194" alt="Project Contract" src="https://user-images.githubusercontent.com/63241209/92888805-ef082380-f415-11ea-9785-c842006c76c9.png">

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
 Any

**Additional context**
-

**Comment by cristobalcampr** [comment]
done
