### ISSUE TITLE
Able to create new projects with regular "user" role

### ISSUE THREAD

**Issue by CAMPR-Manuel** [CamprGmbH/campr#47]
Currently, when clicking on projects (dashboard) I'm able to create new project as a user with role "user" in a workspace. This should not be possible! Only admins (incl. super admin) shall be able to do so! 

![2020-05-05 11 41 01](https://user-images.githubusercontent.com/63241209/81053441-5db3fe00-8ec5-11ea-8ba5-acafee5be600.jpg)

**Comment by maxlenash** [comment]
done and merged to develop
