### ISSUE TITLE
Swapping tasks between projects 

### ISSUE THREAD

**Issue by CAMPR-Manuel** [CamprGmbH/campr#48]
Within one workspace, tasks are swapping between projects. The tasks of one project appear in the project dashboard of another project. 
Also sometime the task list within the project dashboard stays blank while tasks are existing in this project. 
Using Safari on MacOS

[200505_CAMPR_swapping tasks.mov.zip](https://github.com/CamprGmbH/campr/files/4580036/200505_CAMPR_swapping.tasks.mov.zip)

**Comment by cristobalcampr** [comment]
works, thanx! please deploy on prod.
