### ISSUE TITLE
Email notification after creating a task

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#50]
After creating a task the corresponding email with the link 'Task Profile' is send out. The link itself is correct but there's an issue with showing the task details after clicking the link:

- showing the task details works only when
  - the user is logged in into CAMPR **AND**
  - the user is logged in into the workspace the project belongs to

- is the user **not** logged in and he passes the login procedure, he will end up in the workspace view instead seeing the task details

In any case, the user, whether online or offline, must land in the task details when clicking the link.

**Comment by maxlenash** [comment]
done and merged to develop
