### ISSUE TITLE
Email notification text 

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#51]
After creating a task the user is receiving an email notification. Please add the following topics to the notification text:

- Workspace name
- Project name
- creator of the task

**Comment by cristobalcampr** [comment]
Hi @DiliBau , it works and the information are in as required. 

Would it be possible to solve the representation in the email for better readability as follows:
*************************************************************************************************
Hello Christoph Pohl, 
Christoph Pohl created a new task "NOTIFICATION TEST" with due date 2020-06-26 for you.

Workspace: GREINER_ENNS
Project: STATUSTEST
Taskname: NOTIFICATION TEST

Task Profile
*************************************************************************************************

**Comment by cristobalcampr** [comment]
in combination with issue #50

**Comment by maxlenash** [comment]
Done and checked. Should be merged

**Comment by maxlenash** [comment]
merged to develop
