### ISSUE TITLE
Email notification after sending meeting notification

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#52]
After sending a notification for a new meeting, an email with the link to the corresponding meeting details is send out. The link itself is correct but there's an issue with showing the meetingh details after clicking the link (_Please see issue #50 as well, it's the same story ..._):

Showing the meetingdetails works only when

- the user is logged in into CAMPR AND

- the user is logged in into the workspace the project belongs to
- is the user not logged in and he passes the login procedure, he will end up in the workspace view instead seeing the meetingdetails

In any case, the user, whether online or offline, must land in the meeting details when clicking the link.

**Comment by maxlenash** [comment]
done by issues/50. Should recheck

**Comment by maxlenash** [comment]
@cristobalcampr  could you give me link to page for creating meeting please?
Thank you.

**Comment by HannesCAMPR** [comment]
https://campr-tutorials.campr.cloud/#/projects/2/meetings
You can create meetings in this module and send invitations if you have a meeting that takes place in the future.

**Comment by maxlenash** [comment]
done
