### ISSUE TITLE
Avatar in user settings

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#55]
In the settings it must be explicitly defined that an avatar can be loaded. Currently this is not visible or clearly explained to a new user. It is currently not clear what can be loaded. See attachment.

![avatar](https://user-images.githubusercontent.com/63307779/85204768-048a1780-b317-11ea-837c-bf3cf05a34b0.PNG)

**Comment by CAMPR-Manuel** [comment]
Please add text-field with following content: 

UPLOAD PROFILE PHOTO
