### ISSUE TITLE
Project duration

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#56]
When running through the Project Wizard, the defined start/end dates are transferred directly to the 'Project Contract' module. Example see attachment:

Start date: Always the current date
End date: Current date plus 3 months

![wizard](https://user-images.githubusercontent.com/63307779/85204886-ea046e00-b317-11ea-9feb-7f273f9479d2.PNG)

**Comment by HannesCAMPR** [comment]
Project creation wizard:
https://campr-tutorials.campr.cloud/#/projects/create/step/2
Project Contract:
https://campr-tutorials.campr.cloud/#/projects/1/contract

**Comment by maxlenash** [comment]
done in branch issues/56

**Comment by maxlenash** [comment]
merged to develop
