### ISSUE TITLE
Modules at small projects

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#57]
For very small projects, the sliders in the Project Wizard may all be on the left. However, the following modules must be created for these small projects:

- Contract
- Organisation
- Tasks
- Status Report
- Close Down Report

See attachment

![wizard_II](https://user-images.githubusercontent.com/63307779/85204982-86c70b80-b318-11ea-8287-5af47eec2efe.PNG)

**Comment by maxlenash** [comment]
done

**Comment by HannesCAMPR** [comment]
Feedback:
Only the five mentioned in the issue description need to be locked during the project creation wizard step three. Even in large projects for which all modules are suggested, the user needs to be able to deselect the modules that are not needed during the step	three of the project creation wizard.

**Comment by maxlenash** [comment]
done but not deployed
