### ISSUE TITLE
RASCI matrix

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#58]
When changing the responsibilities in the RASCI matrix, an email notification must be sent to the affected users.

The phases are currently displayed unsorted in the RASCI Matrix. In the future, the phases must be displayed in sorted order according to their chronological order.

**Comment by HannesCAMPR** [comment]
Works as intended, we will have to change the email text in the future though. Please use the following wording in the Email according the other notifications, see sample:

> Hello <user name>.
> Your role for the task #14 KICK OFF has changed from Responsible to Support.
> Workspace: TEST WS IMPLTECH TICKETS
> Project: IMPLTECH ISSUE TEST
> Creator of the task: Christoph Pohl

The email notification has to sent to both users. The one who held RESPONSIBLE before (see above) and the new one is RESPONSIBLE now (see below)! For both email notification subject should be ‘Task responsibility changed’

> Hello <user name>,
> Your role for KICK OFF is responsible
> Workspace: TEST WS IMPLTECH TICKETS
> Project: IMPLTECH ISSUE TEST
> Creator of the task: Christoph Pohl

**Comment by cristobalcampr** [comment]
text update

Hello .
Your role for the task #14 KICK OFF has changed from Responsible to Support.
Workspace: TEST WS IMPLTECH TICKETS
Project: IMPLTECH ISSUE TEST
Creator of the task: Christoph Pohl

The email notification has to sent to both users. The one who held RESPONSIBLE before (see above) and the new one is RESPONSIBLE now (see below)! For both email notification subject should be ‘Task responsibility changed’

Hello ,
Your role for KICK OFF is responsible
Workspace: TEST WS IMPLTECH TICKETS
Project: IMPLTECH ISSUE TEST
~~Creator of the task: Christoph Pohl~~
