### ISSUE TITLE
Project Contract

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#59]
Start and end date of a project are automatically taken from the Project Wizard as described in Feature Request #56.

The 'Approved' slider automatically sets the project status to 'In Progress'. See attachment

![approved](https://user-images.githubusercontent.com/63307779/85205135-89763080-b319-11ea-804c-498912d6e855.PNG)

**Comment by cristobalcampr** [comment]
Changes in the document should be saved automatically also without explicetly SAVING the content. Example: TASK MANAGEMENT, here we save automatically during edit.

**Comment by HannesCAMPR** [comment]
To be found here:
https://campr-tutorials.campr.cloud/#/projects/1/contract

**Comment by maxlenash** [comment]
done and merged
