### ISSUE TITLE
RASCI - Change of role 'Responsible'

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#60]
A team member who is responsible for a task is marked with the role **R** in the RASCI.

It is currently possible to withdraw **R** from this team member without first assigning a new team member with R.

The new workflow:

1. Assignment with R of the NEW team member
2. Withdrawal of R from the previous responsible person

**Comment by Tanzorr** [comment]
Can you put exactly the link for the task edit page with connecting with this issue?

**Comment by HannesCAMPR** [comment]
The issue appears in the module RASCI Matrix: https://campr-tutorials.campr.cloud/#/projects/1/rasci-matrix

**Comment by Tanzorr** [comment]
thanks
