### ISSUE TITLE
Link to GitHub/ youtube

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#61]
The following changes are implemented in each module:

- Omission of the previous button 'User Feedback
- Implementation button for Github 'Bug/ Feature Report
- Implementation of the youtube tutorial for this module

See attachment

![tutorial](https://user-images.githubusercontent.com/63307779/85205341-26859900-b31b-11ea-8fdd-855d250825cc.PNG)

**Comment by HannesCAMPR** [comment]
Please use the following links:
https://www.youtube.com/channel/UCgP6VLB0CJdRznCFBiRh5BQ/playlists?view_as=subscriber
https://github.com/CamprGmbH

**Comment by maxlenash** [comment]
done and merged to develop

**Comment by HannesCAMPR** [comment]
Further changes
- Change “GitHub” to “Feedback” with following link: https://github.com/CamprGmbH/campr/issues
- Change “YouTube” to “Tutorial”, link remains the same.
- remove feedback widget on the right hand side.

**Comment by maxlenash** [comment]
done
