### ISSUE TITLE
Assigment task to project phase

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#62]
When a new task is created and the new task is assigned at the same time, a plausibility check and, if necessary, a warning must be issued.

Example screenshot
- Phase 'Project Management' lasts from 29.03.19 - 30.06.20
- The new task should have the end date 10.30.20. This would be wrong, since the pahse already ends on 30.06.20.
- An assignment would not be possible in this case, a plausibility check must be performed when creating the task.

see attachment

![task](https://user-images.githubusercontent.com/63307779/85205609-b5df7c00-b31c-11ea-9143-f78c841a421e.PNG)

**Comment by cristobalcampr** [comment]
- option 1: adapt start/ end date of new task
- option 2: adapt correponding phase dates

**Comment by HannesCAMPR** [comment]
To be found here:
https://campr-tutorials.campr.cloud/#/projects/1/task-management/list

**Comment by HannesCAMPR** [comment]
Information about the functionality of Phases&Milestones and Tasks:
https://www.youtube.com/watch?v=wztXAohf3vk&t=2s
https://www.youtube.com/watch?v=bvQQVLxbVZw&t=14s

**Comment by CAMPR-Manuel** [comment]
We discussed this internally again and would prefer the following, more simple solution: 
If the start and/or end dates of a new task don't match with the start- and end dates of the assigned phase or milestone (which is then assigned to a phase), means: 

1. Start-date task < Start-date phase
2. End-date task > End-date phase / or milestone date
3. Both

Then a message should pop-up containing the following information: 

- "The scheduled task dates don't match with the dates of the phase or milestone" Followed by the phase name (or milestone) and the start- and end dates of the phase (end-date of the milestone) -

This is valid as soon as the task is assigned to a phase or to a milestone which is assigned to a phase. 

In case of a milestone, the phase start date and the milestone (end-) dates are used for this validation. 

The user is unable to save the task while dates don't match with the phase (milestone).
