### ISSUE TITLE
Duplicate a project

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#63]
An existing project can be duplicated within the same workspace.

Currently, duplicating works, but the start and end date of the duplicated project and the start and end dates of the task it contains are not recalculated.

Future workflow:
- Start date of the duplicated project: current date
- End date of the duplicated project: Determined by forward calculation

See attachment

![duplicate](https://user-images.githubusercontent.com/63307779/85205937-d4467700-b31e-11ea-97ed-74b0b60dd0bd.PNG)

**Comment by CAMPR-Manuel** [comment]
[200805_CAMPR_Project Duplicate Calc.pdf](https://github.com/CamprGmbH/campr/files/5027686/200805_CAMPR_Project.Duplicate.Calc.pdf)

Hi @maxlenash here is an example of a project we can run a test with. 
1. First project is called: 'ProjectDateShift'. 
2. Duplicating this project, naming it 'Duplicated ProjectDateShift' and picking the start date August 12th
3. After duplicating, all phases, tasks and milestone shall remain with the same duration but have recalculated start and end dates (in this case plus 9 days). 

For user we need to input fields when duplicating the project: 
1. name of new (duplicated) project (as is implemented already)
2. Date field for project start date (by default it should value of today)

Please let me know if anything is unclear.

**Comment by maxlenash** [comment]
ok. 
But Project hasn't start-date and end-date.
Only tasks and phases have start-date and finish-date

**Comment by HannesCAMPR** [comment]
Feedback:
Start date of new duplicated project in the dashboard is incorrect (still same as original)
![image](https://user-images.githubusercontent.com/63300071/91831344-3f2bfc80-ec44-11ea-9a8e-b3357a908eae.png)
But the duplicated project starts on, see below:
![image](https://user-images.githubusercontent.com/63300071/91831406-50750900-ec44-11ea-9753-1611d3d9f573.png)#

Also: Please change the text field ‘Started at’ into ‘Enter start date of duplicated project’.

**Comment by HannesCAMPR** [comment]
Feedback:
We should see a message popping up with two options when tasks dates are not within phase-dates:
1. Adjust phase dates to match task
2. Adjust task dates to match phase Currently I‘m just not able to save the task and get the warning, that the dates don‘t match the task. As user, I don‘t know what to do then.

**Comment by maxlenash** [comment]
done in local
