### ISSUE TITLE
Todos, Descisions, Infos

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#64]
Todos, decisons and infos can be created WITHOUT error message with end date in the past!

**Comment by cristobalcampr** [comment]
- when creating Todos, decisons and infos with end date in the past at least a warning message shall appear in order to give the user a chance to do like that.

**Comment by HannesCAMPR** [comment]
To be found here:
https://campr-tutorials.campr.cloud/#/projects/1/todos
https://campr-tutorials.campr.cloud/#/projects/1/infos
https://campr-tutorials.campr.cloud/#/projects/1/decisions

**Comment by HannesCAMPR** [comment]
Error message works as intended, but does not have a proper text. Needs to warn the user that the selected date is in the past. 
New text:
"Warning: The selected date is in the past.”
