### ISSUE TITLE
"New Project"-button shown without holding admin rights

### ISSUE THREAD

**Issue by HannesCAMPR** [CamprGmbH/campr#66]
**Describe the bug**
When navigating through workspace you were invited to, but only holding simple “user”-rights, meaning no admin/super-admin right, you can add a project in the WS-Dashboard in the project tab.

**To Reproduce**
1. Log into a workspace where you have the status "user"
2. Click on "Projects" in the left menu
3. You will now be able to add a project and complete the three steps of the project wizard before an error message opens up saying you do not have the admin rights to create new projects

**Expected behavior**
You should not see and be able to interact with the "New Project"- button as a simple user.

**Screenshots**
![200622_add project](https://user-images.githubusercontent.com/63300071/85284033-b9931000-b48e-11ea-8ed8-99d594d7575d.PNG)
![200622_error_access denied](https://user-images.githubusercontent.com/63300071/85284042-be57c400-b48e-11ea-928d-462f832f9529.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest (22.06.20)

**Comment by cristobalcampr** [comment]
ticket #47 describes the same issue.
