### ISSUE TITLE
Status Report - Project condition interaction with trend chart

### ISSUE THREAD

**Issue by HannesCAMPR** [CamprGmbH/campr#67]
**Describe the bug**
When changing project condition in the status report module, the project trend chart does not change in real-time when the status changes. If you save the report, the trend chart changes.

**To Reproduce**
1. Go to module "Status Report"
2. Create a new status report
3. Change the project condition using the "traffic light" on the top of the page
4. Trend chart is supposed change, but changes only occur when saving using the button in the bottom of the page

**Expected behavior**
Real-time change of project trend chart without the need to save

**Screenshots**
![200622_status report trend chart](https://user-images.githubusercontent.com/63300071/85285018-6f129300-b490-11ea-96a8-b4b2b37b58d8.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: latest (22.06.20)

**Comment by Tanzorr** [comment]
Put a link for this page, please.

**Comment by HannesCAMPR** [comment]
https://campr-tutorials.campr.cloud/#/projects/1/status-reports
You need to create a new status report. To create a project trend line you need multiple status report that also need to be some time apart.

**Comment by HannesCAMPR** [comment]
Feedback:
I can see the chart doing something while clicking on the traffic light. But the reaction is incorrect and doesn‘t follow the trend chart rules. The former report is green and I change a new report to green, yellow or red, and the chart refreshes but alwasy shows „+1“. After saving the report, it shows it correct.
