### ISSUE TITLE
time dropdown in meetings

### ISSUE THREAD

**Issue by grinch-ee** [CamprGmbH/campr#68]
**Is your feature request related to a problem? Please describe.**
In your module "Meetings" the dropdown for the start and end time of the meeting is not very user friendly. It would be nice to type in the times instead of being forced to use the dropdown. 

**Describe the solution you'd like**
A responsive input field as well as a smoother solution for the dropdown with maybe only one column to choose hour and minute.

Solution in CAMPR
![CAMPR meeting time setting](https://user-images.githubusercontent.com/68270876/87403189-d2d63a80-c5bc-11ea-8127-c2df9463014c.PNG)
Possible alternative as used in google maps
![alternative time s](https://user-images.githubusercontent.com/68270876/87403193-d5389480-c5bc-11ea-9534-c2915e9ddce4.PNG)

**Comment by HannesCAMPR** [comment]
Thanks for your feedback, we will add it to the board!

**Comment by maxlenash** [comment]
issue already resolved

**Comment by HannesCAMPR** [comment]
Testing: 
1. creating new meeting, selecting times with dropdown & manual input
2. editing existing meeting
3. editing meeting from step 1.
4. rescheduling a future meeting

Feedback:
1. When creating a new meeting the dropdown works smoothly and is accurate enough (15-minute steps, but any other time can be entered manually) and manual input works, too. 
2. When editing the existing meeting, the old dropdown reappeared and the	input field was blocked.
3. See feedback step 2
4. Old dropdown menu also displayed here
