### ISSUE TITLE
Missing Label

### ISSUE THREAD

**Issue by timtam87** [CamprGmbH/campr#69]
I found a minor thing on the project dashboard that should be an easy fix: 
![button view_tasks_grid ohne label](https://user-images.githubusercontent.com/68281785/87577502-45d1d500-c6d3-11ea-8d70-7b511cffbf6e.PNG)
The label for the task grid view is missing..

**Comment by HannesCAMPR** [comment]
To be found here:
https://campr-tutorials.campr.cloud/#/projects/1/dashboard

**Comment by maxlenash** [comment]
done
