### ISSUE TITLE
Selecting a Project Manager

### ISSUE THREAD

**Issue by ritter872** [CamprGmbH/campr#71]
I need some help making a regular project member a project manager. I downloaded the CAMPR manual from your website and saw that it is not possible through the organisation module, but only through the admin section.

I went to project>user to change the project role of the project member, but I only had the choice between Project Sponsor and Team Member. What am I doing wrong? Where can I set the role to Project Manager?

**Comment by HannesCAMPR** [comment]
Good morning ritter872,
Please check the existing project roles in the admin section (Admin section->Project-> Role). Normally you should see three preset roles: Project Sponsor, Project Manager and Team Member. 
If the Project Manager is missing from this list, please add a new role with the following specifications:

Name: roles.project_manager
Sequence: 2
Parent: Project Sponsor

Could you please follow these instructions and let me know if it solved the problem?

Cheers,
Hannes

**Comment by ritter872** [comment]
That did solve the issue - thanks!!
